# version: "3.9"

# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:7.3.2
#     container_name: zookeeper
#     hostname: zookeeper
#     restart: unless-stopped
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#     ports:
#       - "2181:2181"

#   kafka:
#     image: confluentinc/cp-kafka:7.3.2
#     container_name: kafka
#     hostname: kafka
#     restart: unless-stopped
#     depends_on:
#       - zookeeper
#     ports:
#       - "9092:9092"   # client connect từ máy host (localhost)
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

#       # 2 listeners:
#       # - PLAINTEXT://kafka:29092  (container-to-container trong docker network)
#       # - PLAINTEXT_HOST://localhost:9092 (host-to-container từ máy bạn)
#       KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
#       KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

#       # 1 broker thì replication factor phải để 1
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# networks:
#   default:
#     name: infra_kafka

version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092